services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      - TZ=America/Toronto
      - NAME=Media     # share display name
      - USER=media
      - PASS=changeMe123
      - UID=1000
      - GID=1000
      - RW=true        # read-write enabled
    ports:
      - 445:445
    volumes:
      - /mnt/media:/storage
      # - ./smb.conf:/etc/samba/smb.conf
      - ./users.conf:/etc/samba/users.conf
    restart: unless-stopped
