# [global]
#     map to guest = Bad User
#     server min protocol = SMB2
#     server max protocol = SMB3

# [media]
#     path = /shared
#     browsable = yes
#     read only = no
#     guest ok = no
#     valid users = media
#     force user = 1000
#     force group = 1000
#     create mask = 0664
#     directory mask = 0775

# [global]
#         server string = samba
#         idmap config * : range = 3000-7999
#         security = user
#         server min protocol = SMB2

#         # disable printing services
#         load printers = no
#         printing = bsd
#         printcap name = /dev/null
#         disable spoolss = yes

# [Data]
#         path = /storage
#         comment = Shared
#         valid users = @smb
#         browseable = yes
#         writable = yes
#         read only = no
#         force user = root
#         force group = root