networks:
  plex:
    name: plex
    driver: bridge

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=${VERSION}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${PLEX_CONFIG}:/config
      - ${PLEX_MEDIA}:/data/media
    networks:
      - plex
    restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${TAUTULLI_CONFIG}:/config
    ports:
      - 8181:8181
    networks:
      - plex
    restart: unless-stopped
