networks:
  vpn:
    name: vpn
    driver: bridge

services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080/tcp # qbittorrent
    environment: # https://www.reddit.com/r/gluetun/comments/1kpbfs2/the_definitive_howto_for_setting_up_protonvpn/
      - TZ=${TZ}
      - UPDATER_PERIOD=24h
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - BLOCK_MALICIOUS=off
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_CIPHERS=AES-256-GCM
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - HTTPPROXY=off
      - SHADOWSOCKS=off
      # Fix for annoying healthcheck issues
      - HEALTH_TARGET_ADDRESS=google.com:443
      - HEALTH_DURATION_TO_WAIT_AFTER_SUCCESS=15s
      - HEALTH_VPN_DURATION_INITIAL=15s
      - HEALTH_VPN_DURATION_ADDITIONAL=10s
    volumes:
      - ${SSD_PATH}/configs/vpn-config:/gluetun
      - ./auth:/gluetun/auth
    networks:
      - vpn
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      vpn:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${SSD_PATH}/configs/qbittorrent-config:/config
      - ${NAS_PATH}:/data
    network_mode: "service:vpn"
    restart: unless-stopped
