networks:
  arrs:
    name: arrs
    driver: bridge
  qbit:
    external: true
    name: qbit

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${HOST_PATH_DATA}:/data
      # - ${RADARR_MOVIES}:/movies
      # - ${RADARR_DOWNLOADS}:/downloads
    ports:
      - 7878:7878
    networks:
      - qbit
      - arrs
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${HOST_PATH_DATA}:/data
      # - ${SONARR_TV}:/tv
      # - ${SONARR_DOWNLOADS}:/downloads
    ports:
      - 8989:8989
    networks:
      - qbit
      - arrs
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PROWLARR_CONFIG}:/config
    ports:
      - 9696:9696
    networks:
      - qbit
      - arrs
    restart: unless-stopped

  notifiarr:
    image: golift/notifiarr:latest
    container_name: notifiarr
    hostname: notifiarr
    volumes:
      - ${NOTIFIARR_CONFIG}:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    ports:
      - 5454:5454
    networks:
      - qbit
      - arrs
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    volumes:
      - ${FLARESOLVERR_CONFIG}:/config
    ports:
      - "8191:8191"
    networks:
      - arrs
    restart: unless-stopped
