services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB
    volumes:
      - ${STIRLING_PDF_HOME_DIR}/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ${STIRLING_PDF_HOME_DIR}/extraConfigs:/configs
      - ${STIRLING_PDF_HOME_DIR}/customFiles:/customFiles/
      - ${STIRLING_PDF_HOME_DIR}/logs:/logs/
      - ${STIRLING_PDF_HOME_DIR}/pipeline:/pipeline/
    ports:
      - '8282:8080'
    restart: unless-stopped

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_KEY=base64:If+vMWX2VsbDp/rww4w7YdAXwe3G39oNhWeC4j5wkNc=
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 13 * * 6 #optional - every Saturday at 1pm
      - PRUNE_RESULTS_OLDER_THAN=30 #optional
    volumes:
      - ${SPEEDTEST_HOME_DIR}:/config
    ports:
      - 8765:80
    restart: unless-stopped
